name: DeployAli

on:
  push:
    branches:
      - main

env:
  TARGET_DIR: /www/web/keepAccount

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy files to server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: 'welcome CPP server'
          LASTSSH: 'after copying success'
        with:
          host: ${{secrets.ALI_ADDRESS}}
          user: 'root'
          pass: ${{ secrets.ALI_PASSWORD }}
          connect_timeout: 20s
          first_ssh: |-
            rm -rf $TARGET_DIR
            echo $WELCOME   
            mkdir -p $TARGET_DIR
          scp: |-
            './*' => $TARGET_DIR/
          last_ssh: |-
            cd $TARGET_DIR
            pwd
            echo $HOME
            npm -v
            node -v
            pnpm -v
            pnpm install
            pnpm run build
            pm2 start -- DB_PWD=${{ secrets.ALI_PASSWORD }} DB_HOST=${{secrets.ALI_ADDRESS}}
            pm2 list
