name: DeployAli

on:
  push:
    branches:
      - main
env:
  TARGET_DIR: /www/web/keepAccount
  TARGET_DIR_Code_Public: /www/web/keepAccount/code/public
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy files to server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          DB_PWD: ${{ secrets.ALI_DB_PWD }}
          DB_USER: ${{ secrets.ALI_DB_USER }}
          DB_HOST: ${{ secrets.ALI_DB_HOST }}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          JWT_EXPIRES_IN: ${{secrets.JWT_EXPIRES_IN}}
          APP_ID: ${{secrets.APP_ID}}
          APP_SECRET: ${{secrets.APP_SECRET}}
        with:
          host: ${{secrets.ALI_ADDRESS}}
          user: 'root'
          pass: ${{secrets.ALI_PASSWORD}}
          connect_timeout: 60s
          first_ssh: |-
            cd $TARGET_DIR/code
            ls
            cp -r public  ../public
            rm -rf code
            mkdir -p code
          scp: |-
            './*' => $TARGET_DIR/code/
          last_ssh: |-
            cd $TARGET_DIR
            cp -r public ./code
            cd $TARGET_DIR/code
            pnpm install
            pnpm run build
            touch ecosystem.config.js
            echo "module.exports = { apps : [ { name: 'my-nestjs-ka', instances: 2,exec_mode: 'cluster', script: './dist/main.js', env: { NODE_ENV: 'production',DB_DATABASE: 'cost',DB_PWD: '${DB_PWD}',DB_USER: '${DB_USER}',DB_HOST: '${DB_HOST}',JWT_EXPIRES_IN: '${JWT_EXPIRES_IN}' ,JWT_SECRET: '${JWT_SECRET}', APP_ID: '${APP_ID}', APP_SECRET: '${APP_SECRET}' } } ] };" > ecosystem.config.js
            pm2 restart ecosystem.config.js
